version: '3.7'

services:
  app:
    container_name: app
    image: newsletter-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./newsletter_backend:/newsletter_backend
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_main